CREATE TABLE MEMBER(
	USER_NO NUMBER(10)
    ,USER_ID VARCHAR2(15)
    ,USER_PW VARCHAR2(20)
    ,USER_PHONE VARCHAR2(15)
    ,USER_EMAIL VARCHAR2(20)
);

CREATE SEQUENCE TB_MEMBER_SEQ_USER_NO
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 1000000;

SELECT TB_MEMBER_SEQ_USER_NO.NEXTVAL FROM DUAL;
SELECT TB_MEMBER_SEQ_USER_NO.CURRVAL FROM DUAL;

-- IDã��
SELECT count(*)
FROM MEMBER 
WHERE USER_ID = 'ejyoo';

-- ID�� �ش��ϴ� pw Ȯ�� ��ġ�ϴ��� Ȯ��
SELECT count(*)
FROM MEMBER 
WHERE USER_ID = 'ejyoo' AND USER_PW = 'dmswl123';

-- �α��� ��� �� ��ȯ
SELECT 
    USER_ID
    ,USER_PW
    ,USER_PHONE
    ,USER_EMAIL
FROM MEMBER 
WHERE USER_ID = 'ejyoo' AND USER_PW = 'dmswl123';

SELECT 
    USER_ID userId
    ,USER_PW userPw
    ,USER_PHONE userPhone
    ,USER_EMAIL userEmail
FROM MEMBER;

INSERT INTO MEMBER(
    USER_ID
    ,USER_PW
    ,USER_PHONE
    ,USER_EMAIL
)VALUES(
    'ejyoo2'
    ,'dmswl123'
    ,'010-7620-3585'
    ,'o3k1@gmail.com'
);

UPDATE MEMBER SET 
    USER_PHONE = '010-0000-0000'
    ,USER_EMAIL = 'o3k1@nate.com'
WHERE USER_ID = 'ejyoo1';

DELETE FROM MEMBER 
WHERE USER_ID = 'ejyoo2';




CREATE TABLE MYBATIS_NOTICE(
	NOTICE_NO NUMBER(10)
    ,NOTICE_TITLE VARCHAR2(30)
    ,NOTICE_CONTENTS VARCHAR2(3000)
    ,NOTICE_WRITER VARCHAR2(15)
    ,NOTICE_EDITER VARCHAR2(15)
    ,NOTICE_CREATE VARCHAR2(20)
    ,NOTICE_MODIFY VARCHAR2(20)
);

CREATE SEQUENCE MYBATIS_NOTICE_SEQ_NOTICE_NO
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 1000000;

SELECT MYBATIS_NOTICE_SEQ_NOTICE_NO.NEXTVAL FROM DUAL;
SELECT MYBATIS_NOTICE_SEQ_NOTICE_NO.CURRVAL FROM DUAL;

INSERT INTO MYBATIS_NOTICE(
     NOTICE_NO
    ,NOTICE_TITLE
    ,NOTICE_CONTENTS
    ,NOTICE_WRITER
    ,NOTICE_EDITER
    ,NOTICE_CREATE
    ,NOTICE_MODIFY
)
VALUES(
    MYBATIS_NOTICE_SEQ_NOTICE_NO.NEXTVAL
    ,'게시글 제목5'
    ,'게시글 내용5'
    ,'벡설이'
    ,'오승택'
    ,TO_CHAR(SYSDATE, 'YY/MM/DD HH24:MI:SS')
    ,''
);

SELECT NOTICE_NO
    ,NOTICE_TITLE
    ,NOTICE_CONTENTS
    ,NOTICE_WRITER
    ,NOTICE_EDITER
    ,NOTICE_CREATE
    ,NOTICE_MODIFY
FROM MYBATIS_NOTICE;

SELECT NOTICE_NO
    ,NOTICE_TITLE
    ,NOTICE_CONTENTS
    ,NOTICE_WRITER
    ,NOTICE_EDITER
    ,NOTICE_CREATE
    ,NOTICE_MODIFY
FROM MYBATIS_NOTICE
WHERE 1=1
AND NOTICE_NO = 2;

SELECT NOTICE_NO
    ,NOTICE_TITLE
    ,NOTICE_CONTENTS
    ,NOTICE_WRITER
    ,NOTICE_EDITER
    ,NOTICE_CREATE
    ,NOTICE_MODIFY
FROM MYBATIS_NOTICE
WHERE 1=1
OR NOTICE_NO = 2
OR NOTICE_TITLE LIKE '%'||'게시글 제목'||'%'
OR NOTICE_CONTENTS = '%'||'게시글 내용'||'%'
OR NOTICE_WRITER = '%'||'유은지'||'%'
OR NOTICE_EDITER = '%'||'오승택'||'%'
OR NOTICE_CREATE = '%'||'21/05/23'||'%'
OR NOTICE_MODIFY IS NULL;

UPDATE MYBATIS_NOTICE 
SET NOTICE_TITLE = '게시글 수정1'
    ,NOTICE_CONTENTS = '게시글 내용1'
    ,NOTICE_EDITER = '김철수'
    ,NOTICE_MODIFY = TO_CHAR(SYSDATE, 'YY/MM/DD HH24:MI:SS')
WHERE NOTICE_NO = 2;

select to_char(sysdate, 'yyyy-mm-dd hh:mi:ss') from dual;
SELECT 
			USER_NO userNo
		    ,USER_ID userId
		    ,USER_PW userPw
		    ,USER_PHONE userPhone
		    ,USER_EMAIL userEmail
		FROM MEMBER;
        
CREATE TABLE MYBATIS_NOTICE(
	NOTICE_NO NUMBER(10)
    ,NOTICE_TITLE VARCHAR2(15)
    ,NOTICE_CONTENTS VARCHAR2(3000)
    ,NOTICE_WRITER VARCHAR2(15)
    ,NOTICE_EDITER VARCHAR2(15)
    ,NOTICE_CREATE VARCHAR2(20)
    ,NOTICE_MODIFY VARCHAR2(20)
);

CREATE SEQUENCE MYBATIS_NOTICE_SEQ_NOTICE_NO
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 1000000;

SELECT MYBATIS_NOTICE_SEQ_NOTICE_NO.NEXTVAL FROM DUAL;
SELECT MYBATIS_NOTICE_SEQ_NOTICE_NO.CURRVAL FROM DUAL;

INSERT INTO MYBATIS_NOTICE(
     NOTICE_NO
    ,NOTICE_TITLE
    ,NOTICE_CONTENTS
    ,NOTICE_WRITER
    ,NOTICE_EDITER
    ,NOTICE_CREATE
    ,NOTICE_MODIFY
)
VALUES(
    MYBATIS_NOTICE_SEQ_NOTICE_NO.NEXTVAL
    ,'게시글 제목5'
    ,'게시글 내용5'
    ,'벡설이'
    ,'오승택'
    ,TO_CHAR(SYSDATE, 'YY/MM/DD HH24:MI:SS')
    ,''
);

SELECT NOTICE_NO
    ,NOTICE_TITLE
    ,NOTICE_CONTENTS
    ,NOTICE_WRITER
    ,NOTICE_EDITER
    ,NOTICE_CREATE
    ,NOTICE_MODIFY
FROM MYBATIS_NOTICE;

SELECT NOTICE_NO
    ,NOTICE_TITLE
    ,NOTICE_CONTENTS
    ,NOTICE_WRITER
    ,NOTICE_EDITER
    ,NOTICE_CREATE
    ,NOTICE_MODIFY
FROM MYBATIS_NOTICE
WHERE 1=1
AND NOTICE_NO = 2;

SELECT NOTICE_NO
    ,NOTICE_TITLE
    ,NOTICE_CONTENTS
    ,NOTICE_WRITER
    ,NOTICE_EDITER
    ,NOTICE_CREATE
    ,NOTICE_MODIFY
FROM MYBATIS_NOTICE
WHERE 1=1
OR NOTICE_NO = 2
OR NOTICE_TITLE LIKE '%'||'게시글 제목'||'%'
OR NOTICE_CONTENTS = '%'||'게시글 내용'||'%'
OR NOTICE_WRITER = '%'||'유은지'||'%'
OR NOTICE_EDITER = '%'||'오승택'||'%'
OR NOTICE_CREATE = '%'||'21/05/23'||'%'
OR NOTICE_MODIFY IS NULL;

UPDATE MYBATIS_NOTICE 
SET NOTICE_TITLE = '게시글 수정1'
    ,NOTICE_CONTENTS = '게시글 내용1'
    ,NOTICE_EDITER = '김철수'
    ,NOTICE_MODIFY = TO_CHAR(SYSDATE, 'YY/MM/DD HH24:MI:SS')
WHERE NOTICE_NO = 9;

DELETE MYBATIS_NOTICE WHERE NOTICE_NO=3;